sudo: required
language: python

services:
  - docker

matrix:
  fast_finish: true

  include:
    - env: DIMAGE="centos_cron_66"
    - env: DIMAGE="centos_cron_7"

before_install:
  - docker build -t wied03/$DIMAGE docker/$DIMAGE

script:
  - "docker run -v `pwd`:/code -w /code -u nonrootuser -t wied03/$DIMAGE ./setup.py test"
