sudo: required
language: ruby
# Adding this to try and get Docker working
dist: trusty

services:
  - docker

matrix:
  fast_finish: true

  include:
    - env: CENTOS="centos66"
    - env: CENTOS="centos67" SKIP_UNIT="true"
    # email vs stdout only differs re: integration
    - env: CENTOS="centos7_email" SKIP_UNIT="true"
    - env: CENTOS="centos7_stdout"

# Docker related permissions issues on Travis
before_install:
  - mkdir -p .eggs
  - chmod a+rwx .eggs
  - mkdir -p centos_package_cron.egg-info
  - chmod a+rwx centos_package_cron.egg-info
  - chmod a+rwx centos_package_cron
  - mkdir -p tests/__pycache__
  - chmod -R a+rwx tests
  - chmod a+rwx .

script:
  - rake --trace
